#    #spring.application.name=shop
#spring:
#  output:
#    ansi:
#      enabled: always
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
##    hibernate.hbm2ddl.auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

spring:
  messages:
    basename: errors
  datasource:
    #    url: jdbc:h2:mem:testdb
    #    driver-class-name: org.h2.Driver
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

file:
  root-path: C:/Users/Home/Desktop/file-repository/
  root-url: /files

server:
  port: 8081